Repository ethereum/remix-ide, pull requests merged in 2018-05, with the labels that each got.

#1290 Fix Call Return Value
  src/universal-dapp-styles.js
Labels: 3 - Review

#1291 [Browser Test] add "from" in event result
  .circleci/config.yml
  test-browser/tests/compiling.js
Labels: review

#1293 Fix gists
  package.json
  src/app.js
  src/app/panels/file-panel.js
  src/app/tabs/settings-tab.js
  src/app/tabs/styles/settings-tab-styles.js
Labels: 3 - Review, review

#1240 refactor debugger tab
  src/app/tabs/debugger-tab.js
  src/app/tabs/styles/debugger-tab-styles.js
Labels: review

#1237 refactor settings
  src/app/tabs/settings-tab.js
Labels: review

#1244 Refactor app.js
  src/app.js
  src/app/editor/editor.js
  src/app/tabs/compile-tab.js
  src/app/tabs/run-tab.js
  src/app/tabs/settings-tab.js
  src/recorder.js
Labels: 3 - Review

#1312 Fix Render warning without msg
  src/app/ui/renderer.js
Labels: 3 - Review

#1307 Multi param angles content
  src/multiParamManager.js
  src/universal-dapp-styles.js
Labels: 2 - Working <= 5

#1320 Add txStatus icon, move expand to the end, add lines between logs
  src/app/execution/txLogger.js
  src/app/panels/styles/terminal-styles.js
  src/app/ui/styles-guide/style-guide.js
Labels: 3 - Review

#1316 Minor update of labels
  src/app/tabs/run-tab.js
Labels: 3 - Review

#1323 don't add instances if the creation fails
  src/app/tabs/run-tab.js
Labels: 3 - Review
