Repository ethereum/remix-ide, pull requests merged in 2018-04, with the labels that each got.

#1224 bump version 0.6.2
  package.json
Labels: review

#1211 Refactor app.js
  src/app.js
  src/app/panels/righthand-panel.js
  src/app/plugin/pluginAPI.js
  src/app/plugin/pluginManager.js
  src/app/tabs/compile-tab.js
  src/app/tabs/run-tab.js
  src/app/tabs/settings-tab.js
  src/recorder.js
Labels: review

#1238 refactor analysis tab
  src/app/tabs/analysis-tab.js
  src/app/tabs/styles/analysis-tab-styles.js
Labels: review

#1255 Fix load accounts
  src/app/tabs/run-tab.js
Labels: 3 - Review, review

#1247 Update team-best-practices.md
  team-best-practices.md
Labels: 3 - Review, review

#1243 Remove uneeded dep && remove uneeded script
  package.json
Labels: 3 - Review, review

#1196 Update plugin API
  src/app/plugin/pluginManager.js
  test-browser/plugin/remix.js
Labels: 3 - Review

#1266 Fix debugging test (comply with 0.4.23 solidity version)
  .circleci/config.yml
  test-browser/tests/ballot.js
Labels: review

#1264 Update README.md
  README.md
Labels: 3 - Review, review

#1268 use path.join
  embark/index.js
Labels: review

#1274 Fix saving file
  src/app.js
  src/app/editor/editor.js
  src/app/files/file-explorer.js
  src/app/files/fileManager.js
Labels: 3 - Review, review

#1212 Multi params component
  package.json
  src/app/tabs/run-tab.js
  src/multiParamManager.js
  src/universal-dapp-styles.js
  src/universal-dapp-ui.js
  test-browser/helpers/contracts.js
  test-browser/tests/ballot.js
  test-browser/tests/compiling.js
  test-browser/tests/units/testRecorder.js
Labels: 2 - Working <= 5

#1273 Update package.json
  package.json
Labels: 3 - Review, review

#1286 Add status field to createTable
  src/app/execution/txLogger.js
Labels: review

#1278 Multi param angles
  src/multiParamManager.js
  src/universal-dapp-styles.js
Labels: review

#1287 Fix open/close for tx logs in terminal from network
  src/app/execution/txLogger.js
Labels: review
