Repository ethereum/remix-ide, pull requests merged in 2020-04, with the labels that each got.

#2687 Fixed collapsing solidity locals panel
  src/app/ui/TreeView.js
  test-browser/tests/remixd.js
Labels: ux

#2694 Enabled Screenshots For Nightwatch In CircleCI
  .circleci/config.yml
  nightwatch.js
Labels: browser tests

#2613 Improved Transaction Log Test
  src/app/components/vertical-icons.js
  src/app/panels/terminal.js
  src/app/tabs/runTab/contractDropdown.js
  src/app/tabs/runTab/settings.js
  src/app/udapp/run-tab.js
  src/app/ui/multiParamManager.js
  src/app/ui/txLogger.js
  src/app/ui/universal-dapp-ui.js
  test-browser/commands/goToVMTraceStep.js
  test-browser/commands/testFunction.js
  test-browser/tests/ballot.js
  test-browser/tests/transactionExecution.js
Labels: browser tests

#2626 Parallel Browser Tests (Firefox & Chrome)
  .circleci/config.yml
  ci/browser_tests.sh
  package-lock.json
  package.json
  seleniumConfig.js
  src/app/panels/terminal.js
  src/app/ui/multiParamManager.js
  test-browser/commands/checkTerminalFilter.js
  test-browser/commands/executeScript.js
  test-browser/commands/rightClick.js
  test-browser/tests/editor.js
  test-browser/tests/fileExplorer.js
  test-browser/tests/generalSettings.js
  test-browser/tests/gist.js
  test-browser/tests/remixd.js
  test-browser/tests/solidityUnittests.js
  test-browser/tests/terminal.js
Labels: browser tests

#2698 Added delay to async/await test
  test-browser/tests/terminal.js
Labels: browser tests, fix

#2690 Update to Deploy & Run docs
  docs/images/a-run-icon.png
  docs/images/a-runtab1a.png
  docs/images/a-runtab2.png
  docs/run.md
Labels: documentation

#2633 Deploy Code To IPFS
  src/app.js
  src/app/tabs/compile-tab.js
  src/app/tabs/runTab/contractDropdown.js
  src/app/tabs/runTab/model/dropdownlogic.js
  src/app/udapp/run-tab.js
  src/blockchain/blockchain.js
  src/publishToStorage.js
  test-browser/commands/renameFile.js
  test-browser/tests/generalSettings.js
  test-browser/tests/terminal.js
Labels: enhancement

#2664 Fix Auto-scroll To Bottom In Terminal
  src/app/panels/terminal.js
Labels: fix

#2634 Update import.md to use release tag when importing from GitHub
  docs/import.md
Labels: documentation

#2705 Added folder and file to publish to gist test
  test-browser/tests/gist.js
Labels: browser tests

#2713 Fixed wrong display of block number and index [block: txIndex:] for transactions in terminal.
  src/app/ui/txLogger.js
Labels: UI, fix

#2718 Fixed wrong position of rename menu
  src/app/ui/contextMenu.js
Labels: UI, fix

#2725 Fix Failing Library Deployment Test
  src/app/ui/universal-dapp-ui.js
  test-browser/commands/getAddressAtPosition.js
  test-browser/tests/libraryDeployment.js
Labels: browser tests, fix

#2720 testing examples added
  docs/images/a-unit-testing-custom-compiler-config.png
  docs/unittesting.md
  docs/unittesting_examples.md
Labels: documentation

#2723 Uncaught Error Solidity Unit Testing Plugin
  src/app/tabs/test-tab.js
Labels: UI, fix

#2715 Disabled 'Run Tests' Button When No Test Is Selected.
  src/app/tabs/test-tab.js
Labels: UI

#2735 Update release-process.md
  release-process.md
Labels: WIP

#2760 Test for plugin reload after webpage refresh
  test-browser/commands/getInstalledPlugins.js
  test-browser/tests/pluginManager.js
Labels: browser tests

#2762 E2E Tests: Upload Local File to File Explorer
  src/app/files/file-explorer.js
  test-browser/tests/fileExplorer.js
Labels: browser tests

#2767 Ipfs Checkbox Fix & E2E Tests
  src/app/tabs/runTab/contractDropdown.js
  test-browser/tests/publishContract.js
Labels: browser tests

#2755 Fetch and compile before debugging
  package-lock.json
  package.json
  src/app.js
  src/app/compiler/compiler-artefacts.js
  src/app/compiler/compiler-helpers.js
  src/app/compiler/compiler-sourceVerifier-fetchAndCompile.js
  src/app/compiler/compiler-utils.js
  src/app/tabs/debugger-tab.js
  src/app/tabs/debugger/debuggerUI.js
  src/app/tabs/debugger/debuggerUI/TxBrowser.js
  src/app/tabs/test-tab.js
  src/remixAppManager.js
  test-browser/tests/runAndDeploy.js
Labels: needs-remix-lib-release

#2783 E2E Tests - Run and Stop
  src/app/tabs/test-tab.js
  test-browser/commands/notContainsText.js
  test-browser/tests/solidityUnittests.js
Labels: browser tests

#2776 static analysis doc updated
  docs/images/a-static-analysis.png
  docs/static_analysis.md
Labels: documentation

#2782 unit testing docs updated
  docs/images/a-unit-testing-feature.png
  docs/images/a-unit-testing-run-result.png
  docs/unittesting.md
Labels: documentation

#2789 Circle CI Parallelism
  .circleci/config.yml
  ci/browser_tests_chrome.sh
  ci/browser_tests_chrome_part1.sh
  ci/browser_tests_chrome_part2.sh
  ci/browser_tests_firefox.sh
  ci/browser_tests_firefox_part1.sh
  ci/browser_tests_firefox_part2.sh
  nightwatch.js
  package.json
  test-browser/tests/ballot.test.js
  test-browser/tests/debugger.test.js
  test-browser/tests/defaultLayout.test.js
  test-browser/tests/editor.test.js
  test-browser/tests/fileExplorer.test.js
  test-browser/tests/generalSettings.test.js
  test-browser/tests/gist.test.js
  test-browser/tests/libraryDeployment.test.js
  test-browser/tests/pluginManager.test.js
  test-browser/tests/publishContract.test.js
  test-browser/tests/recorder.test.js
  test-browser/tests/remixd.test.js
  test-browser/tests/signingMessage.test.js
  test-browser/tests/solidityImport.test.js
  test-browser/tests/solidityUnittests.test.js
  test-browser/tests/specialFunctions.test.js
  test-browser/tests/staticAnalysis.test.js
  test-browser/tests/terminal.test.js
  test-browser/tests/transactionExecution.test.js
  test-browser/tests/workspace.test.js
Labels: browser tests, enhancement

#2791 E2E Tests: Switch To Goerli TestNet.
  test-browser/tests/runAndDeploy.js
Labels: browser tests
